test_that("Group-major headers yield adjacent grouping (expdesign logic)", {
  skip_if_not_installed("stringdist")
  library(stringdist)
  cols <- c("Control_Rep1","Control_Rep2","Treatment_Rep1","Treatment_Rep2")
  d <- expd_dist(cols, method = "lv", p = 0.2)
  th <- sort(unique(as.vector(d)))
  med <- stats::median(th[th != 0], na.rm = TRUE)
  g <- stats::cutree(stats::hclust(stats::as.dist(d)), h = med)
  expect_true(length(g) >= 4)
  expect_true(g[1] == g[2])
  expect_true(g[3] == g[4])
  expect_true(g[1] != g[3])
})

test_that("Interleaved headers still group by condition (expdesign logic)", {
  skip_if_not_installed("stringdist")
  library(stringdist)
  cols <- c("Control_Rep1","Treatment_Rep1","Control_Rep2","Treatment_Rep2")
  d <- expd_dist(cols, method = "lv", p = 0.2)
  th <- sort(unique(as.vector(d)))
  med <- stats::median(th[th != 0], na.rm = TRUE)
  g <- stats::cutree(stats::hclust(stats::as.dist(d)), h = med)
  expect_true(length(g) >= 4)
  expect_true(g[1] == g[3])
  expect_true(g[2] == g[4])
  expect_true(g[1] != g[2])
})

test_that("Non-canonical group labels map to two groups (expdesign logic)", {
  skip_if_not_installed("stringdist")
  library(stringdist)
  cols <- c("G3_Rep1","G3_Rep2","G5_Rep1","G5_Rep2")
  d <- expd_dist(cols, method = "lv", p = 0.2)
  th <- sort(unique(as.vector(d)))
  med <- stats::median(th[th != 0], na.rm = TRUE)
  g <- stats::cutree(stats::hclust(stats::as.dist(d)), h = med)
  expect_true(length(g) >= 4)
  expect_true(g[1] == g[2])
  expect_true(g[3] == g[4])
  expect_true(g[1] != g[3])
})
